name: Auto-assign based on Project column

on:
  project_card:
    types: 
      - moved

jobs:
  auto_assign:
    runs-on: ubuntu-latest

    steps:
      - name: Setup GitHub CLI
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Get Project Card Info
        id: project_info
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PROJECT_ID="PVT_kwDOCxV1Uc4AstoS"
          CARD_ID="${{ github.event.project_card.id }}"
          
          # Fetch the column name using GraphQL
          CARD_INFO=$(gh api graphql -f query='
            query ($cardId: ID!) {
              node(id: $cardId) {
                ... on ProjectCard {
                  column {
                    name
                  }
                  content {
                    ... on Issue {
                      number
                    }
                  }
                }
              }
            }' -f cardId="$CARD_ID")
          
          COLUMN_NAME=$(echo "$CARD_INFO" | jq -r '.data.node.column.name')
          ISSUE_NUMBER=$(echo "$CARD_INFO" | jq -r '.data.node.content.number')

          echo "Column found: $COLUMN_NAME"
          echo "column_name=$COLUMN_NAME" >> $GITHUB_ENV
          echo "issue_number=$ISSUE_NUMBER" >> $GITHUB_ENV

      - name: Extract Issue Body Information
        id: issue_body
        run: |
          ISSUE_BODY=$(gh issue view $ISSUE_NUMBER --json body --jq .body)
          echo "$ISSUE_BODY" > issue_body.json
          
          RESPONSABILE_STESURA=$(echo "$ISSUE_BODY" | jq -r '.responsabile_stesura')
          RESPONSABILE_VERIFICA=$(echo "$ISSUE_BODY" | jq -r '.responsabile_verifica')
          RESPONSABILE_APPROVAZIONE=$(echo "$ISSUE_BODY" | jq -r '.responsabile_approvazione')

          echo "Responsabile stesura: $RESPONSABILE_STESURA"
          echo "Responsabile verifica: $RESPONSABILE_VERIFICA"
          echo "Responsabile approvazione: $RESPONSABILE_APPROVAZIONE"

          echo "responsabile_stesura=$RESPONSABILE_STESURA" >> $GITHUB_ENV
          echo "responsabile_verifica=$RESPONSABILE_VERIFICA" >> $GITHUB_ENV
          echo "responsabile_approvazione=$RESPONSABILE_APPROVAZIONE" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Assign based on column
        run: |
          if [[ "$COLUMN_NAME" == "Assegnato" ]]; then
            ASSIGNEE="$responsabile_stesura"
          elif [[ "$COLUMN_NAME" == "In Revisione" ]]; then
            ASSIGNEE="$responsabile_verifica"
          elif [[ "$COLUMN_NAME" == "In Approvazione" ]]; then
            ASSIGNEE="$responsabile_approvazione"
          fi

          echo "Assigning issue to $ASSIGNEE"
          gh issue edit $ISSUE_NUMBER --add-assignee "$ASSIGNEE"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          responsabile_stesura: ${{ env.responsabile_stesura }}
          responsabile_verifica: ${{ env.responsabile_verifica }}
          responsabile_approvazione: ${{ env.responsabile_approvazione }}