name: Update Issue Label on Project Column Move

on:
  project_column:
    types: [moved]

jobs:
  update-issue-label:
    runs-on: ubuntu-latest

    steps:
      - name: Check Issue Column and Update Label
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # GitHub API call to get the project card details
          CARD_INFO=$(gh api "${{ github.event.project_column.project_url }}/columns/${{ github.event.project_column.id }}/cards" --jq '.[0]')

          # Extract issue number from the card's content URL
          ISSUE_NUMBER=$(echo "$CARD_INFO" | jq -r '.content_url | split("/") | .[-1]')

          # Map column names to specific labels (customize as needed)
          case "${{ github.event.project_column.name }}" in
            "Assegnato")
              LABEL_TO_ADD="status: stesura"
              LABELS_TO_REMOVE=("status: verifica" "status: approvazione")
              ;;
            "In Revisione")
              LABEL_TO_ADD="status: verifica"
              LABELS_TO_REMOVE=("status: stesura" "status: approvazione")
              ;;
            "In Approvazione")
              LABEL_TO_ADD="status: approvazione"
              LABELS_TO_REMOVE=("status: verifica" "status: stesura")
              ;;
            *)
              echo "No specific label changes for this column"
              exit 0
              ;;
          esac

          # Check if an issue number was successfully extracted
          if [ -z "$ISSUE_NUMBER" ]; then
            echo "Could not extract issue number"
            exit 1
          fi

          # Add the new label
          gh issue edit $ISSUE_NUMBER --add-label "$LABEL_TO_ADD"

          # Remove conflicting labels
          for label in "${LABELS_TO_REMOVE[@]}"; do
            gh issue edit $ISSUE_NUMBER --remove-label "$label" || true
          done
